/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as MyApplicationsRouteImport } from './routes/my-applications'
import { Route as DiagnosticsRouteImport } from './routes/diagnostics'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CampaignsIndexRouteImport } from './routes/campaigns/index'
import { Route as ProfileCreatorRouteImport } from './routes/profile/creator'
import { Route as CampaignsNewRouteImport } from './routes/campaigns/new'
import { Route as CampaignsCampaignIdRouteImport } from './routes/campaigns/$campaignId'
import { Route as CampaignsCampaignIdPartnershipsRouteImport } from './routes/campaigns/$campaignId/partnerships'
import { Route as CampaignsCampaignIdApplyRouteImport } from './routes/campaigns/$campaignId/apply'
import { Route as CampaignsCampaignIdApplicantsRouteImport } from './routes/campaigns/$campaignId/applicants'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const MyApplicationsRoute = MyApplicationsRouteImport.update({
  id: '/my-applications',
  path: '/my-applications',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticsRoute = DiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIndexRoute = CampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileCreatorRoute = ProfileCreatorRouteImport.update({
  id: '/profile/creator',
  path: '/profile/creator',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsNewRoute = CampaignsNewRouteImport.update({
  id: '/campaigns/new',
  path: '/campaigns/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsCampaignIdRoute = CampaignsCampaignIdRouteImport.update({
  id: '/campaigns/$campaignId',
  path: '/campaigns/$campaignId',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsCampaignIdPartnershipsRoute =
  CampaignsCampaignIdPartnershipsRouteImport.update({
    id: '/partnerships',
    path: '/partnerships',
    getParentRoute: () => CampaignsCampaignIdRoute,
  } as any)
const CampaignsCampaignIdApplyRoute =
  CampaignsCampaignIdApplyRouteImport.update({
    id: '/apply',
    path: '/apply',
    getParentRoute: () => CampaignsCampaignIdRoute,
  } as any)
const CampaignsCampaignIdApplicantsRoute =
  CampaignsCampaignIdApplicantsRouteImport.update({
    id: '/applicants',
    path: '/applicants',
    getParentRoute: () => CampaignsCampaignIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/dashboard': typeof DashboardRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/my-applications': typeof MyApplicationsRoute
  '/signin': typeof SigninRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRouteWithChildren
  '/campaigns/new': typeof CampaignsNewRoute
  '/profile/creator': typeof ProfileCreatorRoute
  '/campaigns': typeof CampaignsIndexRoute
  '/campaigns/$campaignId/applicants': typeof CampaignsCampaignIdApplicantsRoute
  '/campaigns/$campaignId/apply': typeof CampaignsCampaignIdApplyRoute
  '/campaigns/$campaignId/partnerships': typeof CampaignsCampaignIdPartnershipsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/dashboard': typeof DashboardRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/my-applications': typeof MyApplicationsRoute
  '/signin': typeof SigninRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRouteWithChildren
  '/campaigns/new': typeof CampaignsNewRoute
  '/profile/creator': typeof ProfileCreatorRoute
  '/campaigns': typeof CampaignsIndexRoute
  '/campaigns/$campaignId/applicants': typeof CampaignsCampaignIdApplicantsRoute
  '/campaigns/$campaignId/apply': typeof CampaignsCampaignIdApplyRoute
  '/campaigns/$campaignId/partnerships': typeof CampaignsCampaignIdPartnershipsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/dashboard': typeof DashboardRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/my-applications': typeof MyApplicationsRoute
  '/signin': typeof SigninRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRouteWithChildren
  '/campaigns/new': typeof CampaignsNewRoute
  '/profile/creator': typeof ProfileCreatorRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/campaigns/$campaignId/applicants': typeof CampaignsCampaignIdApplicantsRoute
  '/campaigns/$campaignId/apply': typeof CampaignsCampaignIdApplyRoute
  '/campaigns/$campaignId/partnerships': typeof CampaignsCampaignIdPartnershipsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/browse'
    | '/dashboard'
    | '/diagnostics'
    | '/my-applications'
    | '/signin'
    | '/campaigns/$campaignId'
    | '/campaigns/new'
    | '/profile/creator'
    | '/campaigns'
    | '/campaigns/$campaignId/applicants'
    | '/campaigns/$campaignId/apply'
    | '/campaigns/$campaignId/partnerships'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/browse'
    | '/dashboard'
    | '/diagnostics'
    | '/my-applications'
    | '/signin'
    | '/campaigns/$campaignId'
    | '/campaigns/new'
    | '/profile/creator'
    | '/campaigns'
    | '/campaigns/$campaignId/applicants'
    | '/campaigns/$campaignId/apply'
    | '/campaigns/$campaignId/partnerships'
  id:
    | '__root__'
    | '/'
    | '/browse'
    | '/dashboard'
    | '/diagnostics'
    | '/my-applications'
    | '/signin'
    | '/campaigns/$campaignId'
    | '/campaigns/new'
    | '/profile/creator'
    | '/campaigns/'
    | '/campaigns/$campaignId/applicants'
    | '/campaigns/$campaignId/apply'
    | '/campaigns/$campaignId/partnerships'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrowseRoute: typeof BrowseRoute
  DashboardRoute: typeof DashboardRoute
  DiagnosticsRoute: typeof DiagnosticsRoute
  MyApplicationsRoute: typeof MyApplicationsRoute
  SigninRoute: typeof SigninRoute
  CampaignsCampaignIdRoute: typeof CampaignsCampaignIdRouteWithChildren
  CampaignsNewRoute: typeof CampaignsNewRoute
  ProfileCreatorRoute: typeof ProfileCreatorRoute
  CampaignsIndexRoute: typeof CampaignsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-applications': {
      id: '/my-applications'
      path: '/my-applications'
      fullPath: '/my-applications'
      preLoaderRoute: typeof MyApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostics': {
      id: '/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof DiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/': {
      id: '/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/creator': {
      id: '/profile/creator'
      path: '/profile/creator'
      fullPath: '/profile/creator'
      preLoaderRoute: typeof ProfileCreatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/new': {
      id: '/campaigns/new'
      path: '/campaigns/new'
      fullPath: '/campaigns/new'
      preLoaderRoute: typeof CampaignsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignId': {
      id: '/campaigns/$campaignId'
      path: '/campaigns/$campaignId'
      fullPath: '/campaigns/$campaignId'
      preLoaderRoute: typeof CampaignsCampaignIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignId/partnerships': {
      id: '/campaigns/$campaignId/partnerships'
      path: '/partnerships'
      fullPath: '/campaigns/$campaignId/partnerships'
      preLoaderRoute: typeof CampaignsCampaignIdPartnershipsRouteImport
      parentRoute: typeof CampaignsCampaignIdRoute
    }
    '/campaigns/$campaignId/apply': {
      id: '/campaigns/$campaignId/apply'
      path: '/apply'
      fullPath: '/campaigns/$campaignId/apply'
      preLoaderRoute: typeof CampaignsCampaignIdApplyRouteImport
      parentRoute: typeof CampaignsCampaignIdRoute
    }
    '/campaigns/$campaignId/applicants': {
      id: '/campaigns/$campaignId/applicants'
      path: '/applicants'
      fullPath: '/campaigns/$campaignId/applicants'
      preLoaderRoute: typeof CampaignsCampaignIdApplicantsRouteImport
      parentRoute: typeof CampaignsCampaignIdRoute
    }
  }
}

interface CampaignsCampaignIdRouteChildren {
  CampaignsCampaignIdApplicantsRoute: typeof CampaignsCampaignIdApplicantsRoute
  CampaignsCampaignIdApplyRoute: typeof CampaignsCampaignIdApplyRoute
  CampaignsCampaignIdPartnershipsRoute: typeof CampaignsCampaignIdPartnershipsRoute
}

const CampaignsCampaignIdRouteChildren: CampaignsCampaignIdRouteChildren = {
  CampaignsCampaignIdApplicantsRoute: CampaignsCampaignIdApplicantsRoute,
  CampaignsCampaignIdApplyRoute: CampaignsCampaignIdApplyRoute,
  CampaignsCampaignIdPartnershipsRoute: CampaignsCampaignIdPartnershipsRoute,
}

const CampaignsCampaignIdRouteWithChildren =
  CampaignsCampaignIdRoute._addFileChildren(CampaignsCampaignIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrowseRoute: BrowseRoute,
  DashboardRoute: DashboardRoute,
  DiagnosticsRoute: DiagnosticsRoute,
  MyApplicationsRoute: MyApplicationsRoute,
  SigninRoute: SigninRoute,
  CampaignsCampaignIdRoute: CampaignsCampaignIdRouteWithChildren,
  CampaignsNewRoute: CampaignsNewRoute,
  ProfileCreatorRoute: ProfileCreatorRoute,
  CampaignsIndexRoute: CampaignsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
